### ISSUE TITLE
Need a class to take screenshots

### ISSUE THREAD

**Issue by dhruvtaneja** [dp-coders/floater#1]
Prepare a class that takes a screenshot and returns the path of the image. You can have the language of your choice. Make sure to meet the following requirements - 
 - return a Uri of file
 - handle permissions
 - try to optimize for frequent screenshot requests (can be done later)
 - create a demo for the same

**Comment by prateekgarg** [comment]
What would the demo entail? Can you elaborate on that requirement?

**Comment by prateekgarg** [comment]
I have a public method added that returns the path. Will make the changes to return URI in next PR
